const brandCommissions = [
  {
    brand: "Honda",
    activeBatches: 3,
    employees: 12,
    totalCommissions: 45230.5,
    avgCommission: 3769.21,
    status: "active",
  },
  {
    brand: "Acura",
    activeBatches: 2,
    employees: 8,
    totalCommissions: 32100.75,
    avgCommission: 4012.59,
    status: "active",
  },
  {
    brand: "Mazda",
    activeBatches: 4,
    employees: 10,
    totalCommissions: 28800.25,
    avgCommission: 2890.03,
    status: "processing",
  },
  {
    brand: "Volkswagen",
    activeBatches: 1,
    employees: 5,
    totalCommissions: 15600,
    avgCommission: 3120,
    status: "active",
  },
  {
    brand: "Ford",
    activeBatches: 5,
    employees: 18,
    totalCommissions: 67800.9,
    avgCommission: 3766.72,
    status: "active",
  },
  {
    brand: "Jeep",
    activeBatches: 2,
    employees: 11,
    totalCommissions: 41200.3,
    avgCommission: 3745.48,
    status: "processing",
  },
  {
    brand: "Chrysler",
    activeBatches: 1,
    employees: 6,
    totalCommissions: 18500,
    avgCommission: 3083.33,
    status: "active",
  },
  {
    brand: "Dodge",
    activeBatches: 3,
    employees: 13,
    totalCommissions: 39400.5,
    avgCommission: 3030.82,
    status: "active",
  },
  {
    brand: "Ram",
    activeBatches: 2,
    employees: 9,
    totalCommissions: 35700.8,
    avgCommission: 3966.76,
    status: "processing",
  },
  {
    brand: "Triumph",
    activeBatches: 1,
    employees: 4,
    totalCommissions: 12300.45,
    avgCommission: 3075.11,
    status: "active",
  },
];

export default brandCommissions;
